{
 "title": "Pathway Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "5a5a4aed", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "pathway" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"pathway\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=~\".*pathway\"} |= ``"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(root_trace_id) (process_memory_usage)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Input Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(root_trace_id) (latency_input)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Output Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(root_trace_id) (latency_output)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Process CPU utime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by(root_trace_id) (process_cpu_utime)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}